name: Tag Track
description: Calculate semantic version bump based on conventional commits
author: David Lopez <davidlopez.hellin@outlook.com>
inputs:
  create-tag:
    description: Create a new tag with bumped version.
    default: false
  push-tag:
    description: Push the new tag to the repository if `create-tag` is used.
    default: false
  github-repo:
    description: Github repository in the format owner/repo, defaults to the repository that triggers the action.
    required: false
  github-token:
    description: Github token to authorize requests to GitHub REST API. Can cause rate limit to be increased.
    required: false
  commit-sha:
    description: Commit SHA from where the version bump will be calculated, defaults to the commit that triggers the action.
    required: false
outputs:
  tag-created:
    description: True if a new tag was created.
    value: ${{ steps.tag-track-runner.outputs.tag-created }}
  old-version:
    description: Old version before calculating the version bump.
    value: ${{ steps.tag-track-runner.outputs.old-version }}
  new-version:
    description: New version after calculating the version bump.
    value: ${{ steps.tag-track-runner.outputs.new-version }}
  error:
    description: Error message if something went wrong.
    value: ${{ steps.tag-track-runner.outputs.error }}
runs:
  using: composite
  steps:
    - name: Add backslash before each / in the repository name
      id: repo-backslash
      shell: bash
      run: |
        echo "github-repo=$(echo $GITHUB_REPOSITORY | sed 's/\//\\\//g' )" >> $GITHUB_OUTPUT
    - name: Get action reference
      shell: bash
      id: action-ref-generator
      run: |
        echo "action-ref=$(echo $GITHUB_ACTION_PATH | sed "s/.*${{ steps.repo-backslash.outputs.github-repo }}\///" )" >> $GITHUB_OUTPUT
    # - name: Download Tag Track
    #   shell: bash
    #   run: |
    #     curl https://raw.githubusercontent.com/dloez/tag-track/${{ steps.action-ref-generator.outputs.action-ref }}/install.sh | sh -s ${{ steps.action-ref-generator.outputs.action-ref }}
    - name: Download Tag Track
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/dloez/tag-track/${{ steps.action-ref-generator.outputs.action-ref }}/install.sh | sh -s 0.8.0
    - name: Calculate version bump
      id: tag-track-runner
      shell: bash
      run: |
        set +e
        command="$HOME/.tag-track/bin/tag-track --output-format json"
        if [ -n "${{ inputs.github-token }}" ]; then
          command="$command --github-token ${{ inputs.github-token }}"
        fi
        if [ -n "${{ inputs.github-repo }}" ]; then
          command="$command --github-repo ${{ inputs.github-repo }}"
        else
          command="$command --github-repo $GITHUB_REPOSITORY"
        fi
        if [ -n "${{ inputs.commit-sha }}" ]; then
          command="$command --commit-sha ${{ inputs.commit-sha }}"
        fi
        if [ -n "${{ inputs.create-tag }}" ]; then
          command="$command --create-tag"
        fi
        echo "::debug::Running command $command"
        tag_track_output="$(eval $command)"
        echo "tag-created=$(echo $tag_track_output | jq -r '.tag_created')" >> $GITHUB_OUTPUT
        echo "old-version=$(echo $tag_track_output | jq -r '.old_version')" >> $GITHUB_OUTPUT
        echo "new-version=$(echo $tag_track_output | jq -r '.new_version')" >> $GITHUB_OUTPUT
        echo "error=$(echo $tag_track_output | jq -r '.error')" >> $GITHUB_OUTPUT
    - name: Check tag-track error
      shell: bash
      if: ${{ steps.tag-track-runner.outputs.error }}
      run: echo ::error::${{ steps.tag-track-runner.outputs.error }} && exit 1
    - name: Push tag
      shell: bash
      if: ${{ steps.tag-track-runner.outputs.created-tag && inputs.push-tag }}
      run: |
        git push origin --tags
