name: Create tag
on:
  push:
    branches:
      - main
jobs:
  call-build_lint:
    uses: ./.github/workflows/build_lint.yml
    secrets: inherit
  create_tag:
    - uses: actions/checkout@v3
    - name: Configure git author
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Setup rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.70.0
        targets: ${{ matrix.os-target.target }}
    - uses: Swatinem/rust-cache@v2
    - name: Run trag-track
      run: cargo run -- --create-tag --github-repo dloez/tag-track --github-token ${{ github.token }}
    - name: Push tags
      run: git push origin --tags
