name: Create tag and release
on:
  push:
    branches:
      - main
jobs:
  call-build_lint:
    uses: ./.github/workflows/build_lint_test.yml
    secrets: inherit
  create-tag:
    runs-on: ubuntu-latest
    needs: call-build_lint
    permissions:
      contents: write
    outputs:
      tag-created: ${{ steps.tag-track.outputs.tag-created }}
      new-tag: ${{ steps.tag-track.outputs.new-tag }}
      new-version: ${{ steps.tag-track.outputs.new-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tag Track
        id: tag-track
        uses: ./
        with:
          create-tag: true
          push-tag: true
          github-token: ${{ github.token }}
          compile: true
          use-cache: true
          tag-track-version: ${{ github.action_ref }}
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: create-tag
    if: ${{ needs.create-tag.outputs.tag-created == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate release notes
        run: |
          sed 's/{version}/${{ needs.create-tag.outputs.new-version }}/g' ${{ github.workspace }}/.github/release_notes.template \
          > ${{ github.workspace }}/.github/release_notes.txt
      - name: Create release
        uses: softprops/action-gh-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          name: Tag Track - ${{ needs.create-tag.outputs.new-version }}
          tag_name: ${{ needs.create-tag.outputs.new-tag }}
          body_path: ${{ github.workspace }}/.github/release_notes.txt
          target_commitish: ${{ github.base_ref }}
          prerelease: true
  upload-to-release:
    needs: [create-tag, release]
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tag-track_${{ matrix.target }}
          path: ${{ github.workspace }}/target/${{ matrix.target }}/release
      - name: Upload tag-track binary to release
        run: |
          mv ${{ github.workspace }}/target/${{ matrix.target }}/release/tag-track${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }} \
          tag-track_${{ matrix.target }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
          gh release upload ${{ needs.create-tag.outputs.new-version }} \
          tag-track_${{ matrix.target }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
