name: Test workflow
on:
  push:
jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: tag-track
      - run: echo ${{ steps.tag-track.outputs.version-api }}
      - run: echo ${{ steps.tag-track.outputs.version-ui }}
